version: "4.9"
services:

  mongo:
    image: 'mongo'
    restart: always
    ports:
      - "27017:27017"
    container_name: GoClean

#  server:
#    build: ./
#    ports:
#      - '8080:8080'
#    depends_on:
#      - mongo
#    environment:
#      - MONGO_URL=mongodb://127.0.0.1:27017
#    container_name: GoClean